In [46]:
from src.kmean import KMeans
from src.kmedoid import KMedoid
from src.dtw import get_dtw_distance
from src.dba import get_approximate_medoid_index
from src.agh import AGH
from src.rdm import RDm

In [47]:
import numpy as np

In [48]:
model_mean = KMeans(2,10,0.1)
model_medoid = KMedoid(2,10,0.1)

In [49]:
X = np.array([[100,100,100], [0.2,0.3,0.4], [0.2,0.4,0.4], [0.3,1.3,0.4]])
dtw_mat = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        dtw_mat[i,j] = get_dtw_distance(X[i,:], X[j,:])

In [50]:
model_mean.fit(X, dtw_mat)

Convergence criterion satisfied before reaching 10 iterations


In [51]:
model_mean.centroids

array([[100.  , 100.  , 100.  ],
       [  0.25,   0.35,   0.85]])

In [52]:
model_medoid.fit(X, dtw_mat)

Convergence criterion satisfied before reaching 10 iterations


In [53]:
model_agh = AGH(2,10,0.1)

In [54]:
get_approximate_medoid_index(dtw_mat, [3], 1)

3

In [55]:
model_agh.fit(X, dtw_mat)

In [56]:
model_agh.centroids

array([[ 0.3,  1.3,  0.4],
       [50.1, 50.2, 50.2]])

In [57]:
model = RDm(2)

In [59]:
model.fit(X)

In [60]:
model.centroids

array([[0.2, 0.3, 0.4],
       [0.2, 0.4, 0.4]])