In [35]:
from src.kmean import kmeans
from src.kmedoid import kmedoid
from src.dtw import get_dtw_distance

In [27]:
import numpy as np

In [36]:
model_mean = kmeans(2,10,0.1)
model_medoid = kmedoid(2,10,0.1)

In [29]:
X = np.array([[100,100,100], [0.2,0.3,0.4], [0.2,0.4,0.4], [0.3,1.3,0.4]])
dtw_mat = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        dtw_mat[i,j] = get_dtw_distance(X[i,:], X[j,:])

In [30]:
model_mean.fit(X, dtw_mat)

{0: [0], 1: [1, 2, 3]}
{0: [0], 1: [1, 2, 3]}


array([[100.  , 100.  , 100.  ],
       [  0.25,   0.35,   0.85]])

In [37]:
model_medoid.fit(X, dtw_mat)

[0 1 1 1]
{0: [0], 1: [1, 2, 3]}
ok
[0 0 0 0]
{0: [0, 1, 2, 3], 1: []}


IndexError: arrays used as indices must be of integer (or boolean) type